/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FinalLetter: typeof import('./src/components/FinalLetter.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    QrCode: typeof import('./src/components/QrCode.vue')['default']
    Reasons: typeof import('./src/components/Reasons.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
  }
}
